### ISSUE TITLE
100.io LFG bot card "spots left" undeclared 

### ISSUE THREAD

**Issue by therarecommoner** [pylaligand/destiny-slack-bot#136]
It seems to have been around since the the change to include it:
https://goo.gl/photos/uhzjd1nZ9UkzaiRX6

Seems though that the issue is present whether there are 1 or 1+ users attached to the event. 
https://goo.gl/photos/Kw3xSxcstBuLyLUg6

**Comment by pylaligand** [comment]
That's only an issue on mobile. The "Platform" and "Spots left" fields are declared as "short", and apparently they really mean it. I'll shorten to "Spots" and that should do it.

**Comment by pylaligand** [comment]
There's still a problem with the "Platform" field. I'll just get rid of short fields altogether.
