### ISSUE TITLE
New bot to check stats for a player to help filter out LFG groups

### ISSUE THREAD

**Issue by john-mikhail** [pylaligand/destiny-slack-bot#170]
Maybe have something similar to the trials bot that shows all the active people in someone's fireteam?  Not sure if it should be a general profiles bot or a wotm-raid one to show # raid completions, etc.?   Maybe combine '/profiles [name] [filter...i.e. wotm, kf, etc']

**Comment by pylaligand** [comment]
#173 contributed too.
